/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("org.jetbrains.kotlinx.dataframe") version "0.14.1"
    kotlin("jvm")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
}

dependencies {
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.2")
    implementation("org.jetbrains.kotlinx:dataframe:0.14.1")
    implementation(kotlin("stdlib-jdk8"))
    testImplementation("org.assertj:assertj-core:3.24.2") // or the latest version

}

group = "org.danwatt"
version = "1.0-SNAPSHOT"
description = "retirement"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.test {
    useJUnitPlatform()
}